### ISSUE TITLE
Two digit millisecond Counter

### ISSUE THREAD

**Issue by Ramkesh9** [dimchoSCR/android-stopwatch#1]
Thanx Admin for a great stopwatch code,but i am facing a problem below:

i required 2 digit millisecond counter instead of 1 digit , so please help me to achieve this.

**Comment by dimchoSCR** [comment]
Hi Ramkesh9, 
sorry I wasn't able to respond quickly, I had to take exams at my university.

Glad you like the app, it's a bit old, though, so I stopped maintaining it a while back.
But don't worry I will gladly extend the stopwatch counter and if something else pops up don't hesitate to write ;).

**Comment by Ramkesh9** [comment]
Hi my Friend, this app is perfect with all stopwatch features, just
excepting 2 digits counter, i merged it in one of my app, the experience
was very good with all required features in one unit. Just require 2 digits
more, thats all
Thanx.

**Comment by dimchoSCR** [comment]
I will commit the improvements as soon as I can, thanks for opening this issue.

**Comment by Ramkesh9** [comment]
Sure, I'll be waiting for improvements.
Thanx, actually i tried some myself, but could not achieve da goal, then i
raised the issue😊

**Comment by dimchoSCR** [comment]
Hi @Ramkesh9, 
I implemented the 2 digit millisecond counter. 
You can see how I implemented the feature and then you can incorporate it in your app. 

Cheers

**Comment by Ramkesh9** [comment]
Wao, thats great :)
i will check it and also merge it in my app,
Great thanx my friend :)

**Comment by dimchoSCR** [comment]
You are welcome! Hope it helped you :wink:
